/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AcceptInvite } from './models/AcceptInvite';
export type { AccountDelivery } from './models/AccountDelivery';
export type { AddonPricingInfo } from './models/AddonPricingInfo';
export type { AddonPurchase } from './models/AddonPurchase';
export type { AddonTier } from './models/AddonTier';
export type { AITemplateCreate } from './models/AITemplateCreate';
export type { AITemplateEdit } from './models/AITemplateEdit';
export type { AppendFiles } from './models/AppendFiles';
export type { AttachmentsConfig } from './models/AttachmentsConfig';
export type { AuthToken } from './models/AuthToken';
export type { AzureBlobStorageDelivery } from './models/AzureBlobStorageDelivery';
export type { BannerNotification } from './models/BannerNotification';
export type { BannerNotificationAction } from './models/BannerNotificationAction';
export type { BoxDriveDelivery } from './models/BoxDriveDelivery';
export type { BoxDrivePickerPayload } from './models/BoxDrivePickerPayload';
export type { BulkGen } from './models/BulkGen';
export type { BulkGenData } from './models/BulkGenData';
export type { BulkGenEdit } from './models/BulkGenEdit';
export type { BulkGenerateMeta } from './models/BulkGenerateMeta';
export type { BulkGenTask } from './models/BulkGenTask';
export type { BulkGenUpload } from './models/BulkGenUpload';
export type { ChangeRole } from './models/ChangeRole';
export type { ChargebeeSubscription } from './models/ChargebeeSubscription';
export type { ChildDocumentMergeHistory } from './models/ChildDocumentMergeHistory';
export type { ChildTemplate } from './models/ChildTemplate';
export type { CopyTemplate } from './models/CopyTemplate';
export type { CSMDetails } from './models/CSMDetails';
export type { DeleteCurrentWorkspace } from './models/DeleteCurrentWorkspace';
export type { DeliveryAccount } from './models/DeliveryAccount';
export type { DeliveryCount } from './models/DeliveryCount';
export type { DemoGraphic } from './models/DemoGraphic';
export type { DocumentMergeHistory } from './models/DocumentMergeHistory';
export type { DocumentMergeLink } from './models/DocumentMergeLink';
export type { DocuSignDelivery } from './models/DocuSignDelivery';
export type { Domain } from './models/Domain';
export type { DomainFailure } from './models/DomainFailure';
export type { DomainVerify } from './models/DomainVerify';
export type { DropboxDelivery } from './models/DropboxDelivery';
export type { DynamicImage } from './models/DynamicImage';
export type { EmailDelivery } from './models/EmailDelivery';
export type { EmailDeliveryAttachment } from './models/EmailDeliveryAttachment';
export type { Envelope } from './models/Envelope';
export type { EnvelopeAttachment } from './models/EnvelopeAttachment';
export type { EnvelopeDetails } from './models/EnvelopeDetails';
export type { EnvelopeDocuments } from './models/EnvelopeDocuments';
export type { EnvelopeHistory } from './models/EnvelopeHistory';
export type { EnvelopeRecipient } from './models/EnvelopeRecipient';
export type { EnvelopeStatusCountResponse } from './models/EnvelopeStatusCountResponse';
export type { EnvelopeVoid } from './models/EnvelopeVoid';
export type { ESignReminderConfig } from './models/ESignReminderConfig';
export type { EversignDelivery } from './models/EversignDelivery';
export type { ExportMergeHistory } from './models/ExportMergeHistory';
export type { File } from './models/File';
export type { FileUploadMeta } from './models/FileUploadMeta';
export type { FillablePdfSettings } from './models/FillablePdfSettings';
export type { Folder } from './models/Folder';
export type { FolderCount } from './models/FolderCount';
export type { FolderSharing } from './models/FolderSharing';
export type { ForbiddenError } from './models/ForbiddenError';
export type { GalleryCategory } from './models/GalleryCategory';
export type { GlobalPermission } from './models/GlobalPermission';
export type { GoogleDriveDelivery } from './models/GoogleDriveDelivery';
export type { GoogleDrivePickerPayload } from './models/GoogleDrivePickerPayload';
export type { HelloSignDelivery } from './models/HelloSignDelivery';
export type { HistoryRecord } from './models/HistoryRecord';
export type { HostedPage } from './models/HostedPage';
export type { InitiateAuthorizationSequence } from './models/InitiateAuthorizationSequence';
export type { Invitation } from './models/Invitation';
export type { MergeHistory } from './models/MergeHistory';
export type { Meta } from './models/Meta';
export type { MoveTemplate } from './models/MoveTemplate';
export type { MoveTemplateResponse } from './models/MoveTemplateResponse';
export type { NewAuthTokenResponse } from './models/NewAuthTokenResponse';
export type { NewTemplate } from './models/NewTemplate';
export type { NotFoundError } from './models/NotFoundError';
export type { NpsNextReminder } from './models/NpsNextReminder';
export type { NpsRating } from './models/NpsRating';
export type { OneDriveDelivery } from './models/OneDriveDelivery';
export type { PaginatedAccountDeliveryList } from './models/PaginatedAccountDeliveryList';
export type { PaginatedBulkGenList } from './models/PaginatedBulkGenList';
export type { PaginatedDocumentMergeHistoryList } from './models/PaginatedDocumentMergeHistoryList';
export type { PaginatedEnvelopeList } from './models/PaginatedEnvelopeList';
export type { PaginatedMergeHistoryList } from './models/PaginatedMergeHistoryList';
export type { PaginatedTemplateList } from './models/PaginatedTemplateList';
export type { PatchedDomain } from './models/PatchedDomain';
export type { PatchedEnvelopeUpdate } from './models/PatchedEnvelopeUpdate';
export type { PatchedUpdateFolderSharing } from './models/PatchedUpdateFolderSharing';
export type { PatchedUpdateNewTemplate } from './models/PatchedUpdateNewTemplate';
export type { PatchedUpdateTemplateSharing } from './models/PatchedUpdateTemplateSharing';
export type { PatchedUpdateUser } from './models/PatchedUpdateUser';
export type { PatchedWorkspace } from './models/PatchedWorkspace';
export type { Plan } from './models/Plan';
export type { PolymorphicDelivery } from './models/PolymorphicDelivery';
export type { PromptSuggestions } from './models/PromptSuggestions';
export type { RenewSubscription } from './models/RenewSubscription';
export type { RestoreTemplateResponse } from './models/RestoreTemplateResponse';
export type { RetentionPreference } from './models/RetentionPreference';
export type { S3Delivery } from './models/S3Delivery';
export type { SaveCustomerFeedback } from './models/SaveCustomerFeedback';
export type { SendEmailAccountAuthorizationOTP } from './models/SendEmailAccountAuthorizationOTP';
export type { SendEnvelopeViaEmail } from './models/SendEnvelopeViaEmail';
export type { SendTestSmtpMail } from './models/SendTestSmtpMail';
export type { SftpDelivery } from './models/SftpDelivery';
export type { SharingInfoFolder } from './models/SharingInfoFolder';
export type { SharingInfoTemplate } from './models/SharingInfoTemplate';
export type { ShowDemographicPrompt } from './models/ShowDemographicPrompt';
export type { ShowUserDomainReservationPrompt } from './models/ShowUserDomainReservationPrompt';
export type { SignableDelivery } from './models/SignableDelivery';
export type { SignatureDelivery } from './models/SignatureDelivery';
export type { SignNowDelivery } from './models/SignNowDelivery';
export type { SurveyPrompt } from './models/SurveyPrompt';
export type { TeamMember } from './models/TeamMember';
export type { Template } from './models/Template';
export type { TemplateCount } from './models/TemplateCount';
export type { TemplateDelivery } from './models/TemplateDelivery';
export type { TemplateGallery } from './models/TemplateGallery';
export type { TemplateInfo } from './models/TemplateInfo';
export type { TemplateMoveFailureDetail } from './models/TemplateMoveFailureDetail';
export type { TemplateSchema } from './models/TemplateSchema';
export type { TemplateSettings } from './models/TemplateSettings';
export type { TemplateSharing } from './models/TemplateSharing';
export type { TemplateTestResponse } from './models/TemplateTestResponse';
export type { Timezone } from './models/Timezone';
export type { TransferOwnership } from './models/TransferOwnership';
export type { UnauthenticatedError } from './models/UnauthenticatedError';
export type { UpdateDeliveryAccount } from './models/UpdateDeliveryAccount';
export type { UpdateRecipientEmail } from './models/UpdateRecipientEmail';
export type { UploadTemplateImage } from './models/UploadTemplateImage';
export type { User } from './models/User';
export type { UserDemographic } from './models/UserDemographic';
export type { UserDomainReservation } from './models/UserDomainReservation';
export type { UserPersonalization } from './models/UserPersonalization';
export type { UserPersonalizationListViewTemplate } from './models/UserPersonalizationListViewTemplate';
export type { ValidationError } from './models/ValidationError';
export type { VerifyDomain } from './models/VerifyDomain';
export type { VerifyEmailAccountOTP } from './models/VerifyEmailAccountOTP';
export type { WebhookDelivery } from './models/WebhookDelivery';
export type { WordAddInPromptSuggestions } from './models/WordAddInPromptSuggestions';
export type { WordAddInTemplateEdit } from './models/WordAddInTemplateEdit';
export type { Workspace } from './models/Workspace';
export type { WorkspaceDemographic } from './models/WorkspaceDemographic';
export type { YouSignDelivery } from './models/YouSignDelivery';

export { AiService } from './services/AiService';
export { AppendService } from './services/AppendService';
export { AuthTokensService } from './services/AuthTokensService';
export { DemographicService } from './services/DemographicService';
export { DomainService } from './services/DomainService';
export { EsignService } from './services/EsignService';
export { FoldersService } from './services/FoldersService';
export { GalleryTemplatesService } from './services/GalleryTemplatesService';
export { GeneralService } from './services/GeneralService';
export { GenerateService } from './services/GenerateService';
export { GenerateBulkService } from './services/GenerateBulkService';
export { HistoryService } from './services/HistoryService';
export { InvitationsService } from './services/InvitationsService';
export { LinkedAccountsService } from './services/LinkedAccountsService';
export { MergeHistoryService } from './services/MergeHistoryService';
export { PermissionsService } from './services/PermissionsService';
export { PersonalizationService } from './services/PersonalizationService';
export { SubscriptionService } from './services/SubscriptionService';
export { TeamService } from './services/TeamService';
export { TemplateDeliveryService } from './services/TemplateDeliveryService';
export { TemplatesService } from './services/TemplatesService';
export { UsersService } from './services/UsersService';
export { UserSatisfactionSurveyService } from './services/UserSatisfactionSurveyService';
export { WorkspacesService } from './services/WorkspacesService';
