name: QC

on:
  pull_request:
    branches: ['**']
    types: [synchronize, opened, reopened, ready_for_review]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false                        # run this job only if the PR is not in a draft state

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        id: setup-node
        with:
          cache: 'npm'
          node-version: '14.18.2'

      - run: npm i

      - name: lint
        run: ./node_modules/.bin/prettier --check **/*.ts
