name: QC

on:
  pull_request:
    branches: [ '**' ]
    types: [ synchronize, opened, reopened, ready_for_review ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false                        # run this job only if the PR is not in a draft state
    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        id: setup-node
        with:
          cache: 'npm'
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/

      - name: Cache node_modules
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-dependencies-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}

      - if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      - name: lint
        run: ./node_modules/.bin/prettier --check **/*.ts
