name: QC

on:
  pull_request:
    branches: [ '**' ]
    types: [ synchronize, opened, reopened, ready_for_review ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false                        # run this job only if the PR is not in a draft state

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        id: setup-node
        with:
          cache: 'npm'
          node-version: '15.14.0'

      - name: Cache node_modules
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-dependencies-15.14.0-${{ hashFiles('package-lock.json') }}

      - name: Cache node_modules
        id: cache-openapi-typescript-codegen-dependencies
        uses: actions/cache@v2
        with:
          path: openapi-typescript-codegen/node_modules
          key: ${{ runner.os }}-dependencies-15.14.0-${{ hashFiles('openapi-typescript-codegen/package-lock.json') }}

      - if: steps.cache-openapi-typescript-codegen-dependencies.outputs.cache-hit != 'true'
        name: install codegen dependencies
        run: |
          cd openapi-typescript-codegen
          npm i
          cd ../

      - name: codegen build
        run: |
          cd openapi-typescript-codegen
          npm run build
          cd ../

      - if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm i

      - name: lint
        run: ./node_modules/.bin/prettier --check **/*.ts
