name: Release

on:
  release:
    types: [ published ]

jobs:
  publish_release_artifacts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.16.0]
    env:
      VERSION: ${{ github.event.release.tag_name }}
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        id: setup-node
        with:
          cache: 'npm'
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/

      - name: replace_version
        run: |
          # update version in package.json with release version
          sed -i 's/"version": "1.0.0"/"version": "'$VERSION'"/g' package.json

      - name: Cache node_modules
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-dependencies-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}

      - if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
