name: Release

on:
  release:
    types: [ published ]

jobs:
  publish_release_artifacts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        id: setup-node
        with:
          cache: 'npm'
          node-version: '14.18.2'

      - name: install
        run: |
          cd openapi-typescript-codegen
          npm i
          npm run build
          cd ../
          npm i

      - name: Compile to es5 (web)
        run: npm run webpack

      - name: Upload Release Asset (Production)
        id: upload-release-asset-production
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_ASSSET_PAT }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/docupilot-js.es5.min.js
          asset_name: docupilot-js.es5.min.js
          asset_content_type: application/javascript

      - name: Upload Release Asset (Development)
        id: upload-release-asset-development
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_ASSSET_PAT }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/docupilot-js.es5.js
          asset_name: docupilot-js.es5.js
          asset_content_type: application/javascript
