name: Release

on:
  release:
    types: [ published ]

jobs:
  publish_release_artifacts:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.release.tag_name }}
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        id: setup-node
        with:
          cache: 'npm'
          node-version: '15.14.0'
          registry-url: https://npm.pkg.github.com/

      - name: replace_version
        run: |
          # update version in package.json with release version
          sed -i 's/"version": "1.0.0"/"version": "'$VERSION'"/g' package.json

      - name: Cache node_modules
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-dependencies-15.14.0-${{ hashFiles('package-lock.json') }}

      - name: Cache node_modules
        id: cache-openapi-typescript-codegen-dependencies
        uses: actions/cache@v2
        with:
          path: openapi-typescript-codegen/node_modules
          key: ${{ runner.os }}-dependencies-15.14.0-${{ hashFiles('openapi-typescript-codegen/package-lock.json') }}

      - if: steps.cache-openapi-typescript-codegen-dependencies.outputs.cache-hit != 'true'
        name: install codegen dependencies
        run: |
          cd openapi-typescript-codegen
          npm i
          cd ../

      - name: codegen build
        run: |
          cd openapi-typescript-codegen
          npm run build
          cd ../

      - if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci

      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
